<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BillboardSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $billboards = [
            [
                'kode_titik' => 'BM 02',
                'lokasi' => 'Jl. Sudirman No. 01 - Bandung',
                'ukuran' => '5m x 10m (H)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 35000000,
                'status' => 'Tersedia',
                'latitude' => -6.920263, // Perempatan Sudirman - Otista
                'longitude' => 107.60273,
            ],
            [
                'kode_titik' => 'BM 03 (A)',
                'lokasi' => 'Jl. Surapati No. 76 - Suci (A) (View dari Gasibu ke Cicaheum) - Bandung',
                'ukuran' => '5m x 10m (H)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 35000000,
                'status' => 'Tersedia',
                'latitude' => -6.899324, // Jalur Utama Jl. Surapati
                'longitude' => 107.632281,
            ],
            [
                'kode_titik' => 'BM 03 (B)',
                'lokasi' => 'Jl. Surapati No. 76 - Suci (B) (View dari Cicaheum ke Gasibu) - Bandung',
                'ukuran' => '5m x 10m (H)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 35000000,
                'status' => 'Tersedia',
                'latitude' => -6.899388,
                'longitude' => 107.632345,
            ],
            [
                'kode_titik' => 'BM 11 (A)',
                'lokasi' => 'Jl. Setiabudi No. 129A - Gerlong Hilir (A) (arah ke Lembang ) - Bandung',
                'ukuran' => '5m x 10m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 35000000,
                'status' => 'Tersedia',
                'latitude' => -6.865328, // Setiabudi - Gerlong
                'longitude' => 107.594042,
            ],
            [
                'kode_titik' => 'BM 11 (B)',
                'lokasi' => 'Jl. Setiabudi No. 129A - Gerlong Hilir (B) (arah ke Setiabudi) - Bandung',
                'ukuran' => '5m x 10m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 35000000,
                'status' => 'Tersedia',
                'latitude' => -6.865412,
                'longitude' => 107.593955,
            ],
            [
                'kode_titik' => 'BM 13',
                'lokasi' => 'Jl. Setiabudi No. 235 - (sebelah Terminal Ledeng) - Bandung',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.860477, // Bahu jalan depan Terminal Ledeng
                'longitude' => 107.593712,
            ],
            [
                'kode_titik' => 'BM 15 (A)',
                'lokasi' => 'Jl. Geusan Ulun - Sumedang (arah ke Cirebon) (A)',
                'ukuran' => '4m x 8m (H)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Sumedang',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.843188,
                'longitude' => 107.921312,
            ],
            [
                'kode_titik' => 'BM 15 (B)',
                'lokasi' => 'Jl. Geusan Ulun - Sumedang (arah ke Bandung) (B)',
                'ukuran' => '4m x 8m (H)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Sumedang',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.843254,
                'longitude' => 107.921245,
            ],
            [
                'kode_titik' => 'BM 16',
                'lokasi' => 'Jl.Simpang Lima Otista - Garut',
                'ukuran' => '5m x 10m (H)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Garut',
                'harga_per_bulan' => 35000000,
                'status' => 'Tersedia',
                'latitude' => -7.218524, // Pusat Simpang Lima Garut
                'longitude' => 107.898822,
            ],
            [
                'kode_titik' => 'BM 17',
                'lokasi' => 'Jl. A.H. Nasution No.95 (Ujungberung samping Ubertos)  A & B',
                'ukuran' => '5m x 10m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 35000000,
                'status' => 'Tersedia',
                'latitude' => -6.917904, // Depan Ubertos Mall
                'longitude' => 107.693412,
            ],
            [
                'kode_titik' => 'BM 20 (A)',
                'lokasi' => 'Jl. Soekarno Hatta No. 575 - Bandung - sekelimus (arah ke Buah Batu) ',
                'ukuran' => '5m x 10m (H)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 35000000,
                'status' => 'Tersedia',
                'latitude' => -6.939221,
                'longitude' => 107.641012,
            ],
            [
                'kode_titik' => 'BM 20 (B)',
                'lokasi' => 'Jl. Soekarno Hatta No. 575 - Bandung - sekelimus (arah ke Samsat) ',
                'ukuran' => '5m x 10m (H)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 35000000,
                'status' => 'Tersedia',
                'latitude' => -6.939315,
                'longitude' => 107.641154,
            ],
            [
                'kode_titik' => 'BM 21 (A)',
                'lokasi' => 'Jl. Buah Batu 206B - Bandung (arah ke Soekarno Hatta) (A)',
                'ukuran' => '5m x 10m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 35000000,
                'status' => 'Tersedia',
                'latitude' => -6.945821, // Jalur utama Buah Batu arah bypass
                'longitude' => 107.625344,
            ],
            [
                'kode_titik' => 'BM 21 (B)',
                'lokasi' => 'Jl. Buah Batu 206B - Bandung (arah ke Laswi) (B)',
                'ukuran' => '5m x 10m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 35000000,
                'status' => 'Tersedia',
                'latitude' => -6.945902,
                'longitude' => 107.625211,
            ],
            [
                'kode_titik' => 'BM 24',
                'lokasi' => 'Jl. Kolonel Masturi Citeureup - Cimahi',
                'ukuran' => '4m x 6m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Cimahi',
                'harga_per_bulan' => 10000000,
                'status' => 'Tersedia',
                'latitude' => -6.877543,
                'longitude' => 107.545811,
            ],
            [
                'kode_titik' => 'BM 25',
                'lokasi' => 'Jl. Jaksanarata - Bojongsoang Bandung',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.968843,
                'longitude' => 107.636652,
            ],
            [
                'kode_titik' => 'BM 29',
                'lokasi' => 'Jl. Mangunreja - Tasikmalaya',
                'ukuran' => '4m x 6m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Tasikmalaya',
                'harga_per_bulan' => 10000000,
                'status' => 'Tersedia',
                'latitude' => -7.362143,
                'longitude' => 108.118921,
            ],
            [
                'kode_titik' => 'BM 32',
                'lokasi' => 'Jl. Leuwi Gajah No. 220 - Cimahi Selatan',
                'ukuran' => '4m x 6m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Cimahi',
                'harga_per_bulan' => 10000000,
                'status' => 'Tersedia',
                'latitude' => -6.903824,
                'longitude' => 107.535811,
            ],
            [
                'kode_titik' => 'BM 34 (A)',
                'lokasi' => 'Jl. Raya Cimindi No. 167 - Cimahi (menuju arah cimahi) (A)',
                'ukuran' => '4m x 8m (H)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Cimahi',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.892411,
                'longitude' => 107.556412,
            ],
            [
                'kode_titik' => 'BM 34 (B)',
                'lokasi' => 'Jl. Raya Cimindi No. 167 - Cimahi (menuju arah bandung) (B)',
                'ukuran' => '4m x 8m (H)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Cimahi',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.892502,
                'longitude' => 107.556501,
            ],
            [
                'kode_titik' => 'BM 35',
                'lokasi' => 'Jl. Sutisna Senjaya - Tasikmalaya',
                'ukuran' => '4m x 8m (H)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Tasikmalaya',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -7.324212,
                'longitude' => 108.223412,
            ],
            [
                'kode_titik' => 'BM 36',
                'lokasi' => 'Jl. Nasional - Ciamis (alun-alun) / Jl. Ir. H. Juanda no 71 - Ciamis',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Ciamis',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -7.327412,
                'longitude' => 108.354112,
            ],
            [
                'kode_titik' => 'BM 40 (A)',
                'lokasi' => 'Jl. Raya Parigi No. 441 (view parigi ke cijulang) - Pangandaran',
                'ukuran' => '4m x 8m (H)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Pangandaran',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -7.698412,
                'longitude' => 108.487412,
            ],
            [
                'kode_titik' => 'BM 40 (B)',
                'lokasi' => 'Jl. Raya Parigi No. 441 (view cijulang ke parigi) - Pangandaran',
                'ukuran' => '4m x 8m (H)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Pangandaran',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -7.698501,
                'longitude' => 108.487502,
            ],
            [
                'kode_titik' => 'BM 42 (A)',
                'lokasi' => 'Jl. Raya Simpang No.438 Padalarang - Kab.Bandung Barat  (lama)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Bandung Barat',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.841412,
                'longitude' => 107.468412,
            ],
            [
                'kode_titik' => 'BM 42 (B)',
                'lokasi' => 'Jl. Raya Simpang No.438 Padalarang - Kab.Bandung Barat  (lama)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Bandung Barat',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.841495,
                'longitude' => 107.468501,
            ],
            [
                'kode_titik' => 'BM 43 (A)',
                'lokasi' => 'Jl. Perjuangan Ciawi - Bandung ke Ciawi (A)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Tasikmalaya',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -7.318412,
                'longitude' => 108.124112,
            ],
            [
                'kode_titik' => 'BM 43 (B)',
                'lokasi' => 'Jl. Perjuangan Ciawi - Ciawi Ke Bandung (B)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Tasikmalaya',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -7.318501,
                'longitude' => 108.124201,
            ],
            [
                'kode_titik' => 'BM 45',
                'lokasi' => 'Jl. Raya Nanjung - Kec, Cimahi selatan',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Cimahi',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.924112,
                'longitude' => 107.541412,
            ],
            [
                'kode_titik' => 'BM 49 (A)',
                'lokasi' => 'Jl. Kiaracondong No. 307 ( Menuju ke Jl. perempatanbinong )',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.932412, // Lampu Merah Kiaracondong - Binong
                'longitude' => 107.636412,
            ],
            [
                'kode_titik' => 'BM 49 (B)',
                'lokasi' => 'Jl. Kiaracondong No. 307 ( Menuju ke Jl. perempatanbinong )',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.932495,
                'longitude' => 107.636501,
            ],
            [
                'kode_titik' => 'BM 51',
                'lokasi' => 'Jl. Sindangkasih - Kabupaten Purwakarta',
                'ukuran' => '4m x 8m (H)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Purwakarta',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.518412,
                'longitude' => 107.442412,
            ],
            [
                'kode_titik' => 'BM 53 (A)',
                'lokasi' => 'Jl. Raya Cimindi No 232 - 246 Bandung (menuju ke Cimahi) (A)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.891841,
                'longitude' => 107.558412,
            ],
            [
                'kode_titik' => 'BM 53 (B)',
                'lokasi' => 'Jl. Raya Cimindi No 232 - 246 Bandung (menuju ke Bandung ) (B)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.891902,
                'longitude' => 107.558501,
            ],
            [
                'kode_titik' => 'BM 55',
                'lokasi' => 'Jl. Raya Simpang No.438 Padalarang - Kab.Bandung Barat  (baru)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Bandung Barat',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.841312,
                'longitude' => 107.468612,
            ],
            [
                'kode_titik' => 'BM 56 (A)',
                'lokasi' => 'Jl. Geger Kalong Girang No.1 - Bandung (A) Setiabudhi arah Ledeng ',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.864841, // Pinggir jalan Setiabudi depan Gerlong
                'longitude' => 107.593812,
            ],
            [
                'kode_titik' => 'BM 56 (B)',
                'lokasi' => 'Jl. Geger Kalong Girang No.1 - Bandung (B) Ledeng arah Setiabudi',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.864902,
                'longitude' => 107.593901,
            ],
            [
                'kode_titik' => 'BM 57',
                'lokasi' => 'Jl. Soekarno Hatta No. 247 RT. 007/005 Situsaeur (Kopo)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.938412, // Lampu merah Bypass Kopo
                'longitude' => 107.592412,
            ],
            [
                'kode_titik' => 'BM 58 (A)',
                'lokasi' => 'Jl. Ir. H. Djuanda No. 346 - Bandung (Arah Simpang Dago)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.874841, // Simpang Dago utama
                'longitude' => 107.618412,
            ],
            [
                'kode_titik' => 'BM 58 (B)',
                'lokasi' => 'Jl. Ir. H. Djuanda No. 346 - Bandung (Arah Terminal Dago)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.874902,
                'longitude' => 107.618501,
            ],
            [
                'kode_titik' => 'BM 59',
                'lokasi' => 'Jl. Gedung Empat No. 78 - Kota Cimahi (Jl. Sriwijaya)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Cimahi',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.888412,
                'longitude' => 107.542412,
            ],
            [
                'kode_titik' => 'BM 62',
                'lokasi' => 'Jl. Trunojoyo - Bandung',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.902412,
                'longitude' => 107.618412,
            ],
            [
                'kode_titik' => 'BM 63',
                'lokasi' => 'Jl. Dayeuh Kolot No. 351 - Kab Bandung',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.984112,
                'longitude' => 107.621412,
            ],
            [
                'kode_titik' => 'BM 64',
                'lokasi' => 'Jl.Cihampelas - Lamping',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.887380302828856,
                'longitude' => 107.60205852761352,
            ],
            [
                'kode_titik' => 'BM 66',
                'lokasi' => 'Jl. Sumatera No. 10 - Bandung',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.912412,
                'longitude' => 107.614812,
            ],
            [
                'kode_titik' => 'BM 68',
                'lokasi' => 'Jl.Soekarno Hatta perempatan jalan Kiaracondong Bandung (SAMSAT)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.946412, // Lampu Merah Kircon - bypass (Samsat)
                'longitude' => 107.638412,
            ],
            [
                'kode_titik' => 'BM 69',
                'lokasi' => 'Jl.Tengah Alun - Alun Majalaya Kab. Bandung',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -7.048412,
                'longitude' => 107.752412,
            ],
            [
                'kode_titik' => 'BM 70',
                'lokasi' => 'Jl. Dipatiukur No. 248',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.891412,
                'longitude' => 107.618412,
            ],
            [
                'kode_titik' => 'BM 71 (A)',
                'lokasi' => 'Jl. Sulanjana No. 13 ',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.901412,
                'longitude' => 107.612412,
            ],
            [
                'kode_titik' => 'BKS 73',
                'lokasi' => 'Jl. Raya Cicalengka Pertigaan (Jl. Raya Barat No. 293 RT 001/002 Cicalengka)',
                'ukuran' => '4m x 8m (H)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -7.028412,
                'longitude' => 107.828412,
            ],
            [
                'kode_titik' => 'BM 74 (A)',
                'lokasi' => 'Jl. Surapati No. 43 View dari Jl. Layang Pasupati ke Jl. Surapati (A)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.898412,
                'longitude' => 107.621412,
            ],
            [
                'kode_titik' => 'BM 74 (B)',
                'lokasi' => 'Jl. Surapati No. 43 View dari Jl. Surapati ke Jl. Layang Pasupati (B)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.898501,
                'longitude' => 107.621502,
            ],
            [
                'kode_titik' => 'BM 76',
                'lokasi' => 'Jl. Dangdeur - rancaekek - Kab. Bandung',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.948412,
                'longitude' => 107.762412,
            ],
            [
                'kode_titik' => 'BM 77',
                'lokasi' => 'Jl. Raya Kopo Sayati  No. 361',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.962412,
                'longitude' => 107.578412,
            ],
            [
                'kode_titik' => 'BM 80',
                'lokasi' => 'Jl. Batujajar Blok Kaum Selatan - Batujajar',
                'ukuran' => '4m x 8m (H)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Bandung Barat',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.912412,
                'longitude' => 107.468412,
            ],
            [
                'kode_titik' => 'BM 81 (A)',
                'lokasi' => 'Jl. Ahmad Yani No. 312 - Bandung (Jl. Supratman - Jl. Jakarta) (A)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.918412,
                'longitude' => 107.632412,
            ],
            [
                'kode_titik' => 'BM 81 (B)',
                'lokasi' => 'Jl. Ahmad Yani No. 312 - Bandung (Jl. Jakarta - Jl. Supratman) (B)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.918501,
                'longitude' => 107.632502,
            ],
            [
                'kode_titik' => 'BM 83',
                'lokasi' => 'Jl. Wanayasa Bojong - Kabupaten Purwakarta',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Purwakarta',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.688412,
                'longitude' => 107.552412,
            ],
            [
                'kode_titik' => 'BM 84 (A)',
                'lokasi' => 'Jl. Raya Kopo Soreang - Borma Katapang (Arah dari Soreang)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.992412,
                'longitude' => 107.541412,
            ],
            [
                'kode_titik' => 'BM 84 (B)',
                'lokasi' => 'Jl. Raya Kopo Soreang - Borma Katapang (Arah ke Soreang)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.992501,
                'longitude' => 107.541502,
            ],
            [
                'kode_titik' => 'BM 86',
                'lokasi' => 'Jl. Peta Perempatan Pelindung Hewan ega - Bandung ',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.932412,
                'longitude' => 107.604812,
            ],
            [
                'kode_titik' => 'BM 87',
                'lokasi' => 'Jl. Pasir Kaliki  (PASKAL 23)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.914841,
                'longitude' => 107.601421,
            ],
            [
                'kode_titik' => 'BM 90',
                'lokasi' => 'Jl. Cimanuk - Bandung ',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.904812,
                'longitude' => 107.614812,
            ],
            [
                'kode_titik' => 'BM 91',
                'lokasi' => 'Jl.Jakarta Depan Persil No. 12',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.914841,
                'longitude' => 107.637512,
            ],
            [
                'kode_titik' => 'BM 93',
                'lokasi' => 'Jl. A. Yani No. 28 RT. 12 RW. 02 Kec. Purwakarta',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Purwakarta',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.558412,
                'longitude' => 107.442412,
            ],
            [
                'kode_titik' => 'BM 94',
                'lokasi' => 'Jl. Dr. Muwardi ( Depan Ikan Bakar Cianjur ) (Dari Bandung ke Cianjur)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Cianjur',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.828412,
                'longitude' => 107.138412,
            ],
            [
                'kode_titik' => 'BM 95 (A)',
                'lokasi' => 'Jl. Raya Kadipaten - Kadipaten (Arah Ke Bandung)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Majalengka',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.748412,
                'longitude' => 108.148412,
            ],
            [
                'kode_titik' => 'BM 95 (B)',
                'lokasi' => 'Jl. Raya Kadipaten - Kadipaten (Arah Ke Cirebon)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Majalengka',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.748501,
                'longitude' => 108.148502,
            ],
            [
                'kode_titik' => 'BM 96 (A)',
                'lokasi' => 'JL. Jendral Achmad Yani - Subang (arah ke Subang)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Subang',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.568421,
                'longitude' => 107.763412,
            ],
            [
                'kode_titik' => 'BM 96 (B)',
                'lokasi' => 'JL. Jendral Achmad Yani - Subang (arah ke Bandung)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Subang',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.568501,
                'longitude' => 107.763502,
            ],
            [
                'kode_titik' => 'BM 105',
                'lokasi' => 'Jl. Raya Oleced No. 50, Desa Manggari - Kuningan ',
                'ukuran' => '4m x 8m (H)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Kuningan',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.984112,
                'longitude' => 108.552412,
            ],
            [
                'kode_titik' => 'BM 106',
                'lokasi' => 'Jl. Jamika No. 70 RT 003 RW 005',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.924112,
                'longitude' => 107.588412,
            ],
            [
                'kode_titik' => 'BM 107',
                'lokasi' => 'Jl. Sumatera (RS. Sariningsih)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.911412,
                'longitude' => 107.613812,
            ],
            [
                'kode_titik' => 'BM 108 (A)',
                'lokasi' => 'Neonbox Jl. Jend. Sudirman Depan Persil No. 163',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Neonbox',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 35000000,
                'status' => 'Tersedia',
                'latitude' => -6.920263,
                'longitude' => 107.60273,
            ],
            [
                'kode_titik' => 'BM 109',
                'lokasi' => 'JL. Dipatiukur ( perempatan Jl. Hasanudin )',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.892412,
                'longitude' => 107.617412,
            ],
            [
                'kode_titik' => 'BM 110 (A)',
                'lokasi' => 'Minitron Jl. Banda Depan Persil No. 40',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Minitron',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 35000000,
                'status' => 'Tersedia',
                'latitude' => -6.904812,
                'longitude' => 107.618412,
            ],
            [
                'kode_titik' => 'BM 111 (A)',
                'lokasi' => 'Neonbox Jl. Ahmad Yani',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Neonbox',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 35000000,
                'status' => 'Tersedia',
                'latitude' => -6.915214,
                'longitude' => 107.632412,
            ],
            [
                'kode_titik' => 'BM 112 (A)',
                'lokasi' => 'Jl. Dr. Setiabudi No. 254 bandung (menuju arah ke lembang)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.858412,
                'longitude' => 107.594112,
            ],
            [
                'kode_titik' => 'BM 112 (B)',
                'lokasi' => 'Jl. Dr. Setiabudi No. 254 bandung (menuju arah ke setiabudi)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.858501,
                'longitude' => 107.594201,
            ],
            [
                'kode_titik' => 'BM 132',
                'lokasi' => 'Jl. Sukajadi 8 & 10 ( Oyen )',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.892412,
                'longitude' => 107.596241,
            ],
            [
                'kode_titik' => 'BM 134 (A)',
                'lokasi' => 'Jl. Cagak - Subang (arah ke Subang)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Subang',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.658412,
                'longitude' => 107.728412,
            ],
            [
                'kode_titik' => 'BM 134 (B)',
                'lokasi' => 'Jl. Cagak - Subang (arah ke Bandung)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Subang',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.658501,
                'longitude' => 107.728502,
            ],
            [
                'kode_titik' => 'BM 143 (A)',
                'lokasi' => 'Neonbox Jl. Cibaduyut',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Neonbox',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 35000000,
                'status' => 'Tersedia',
                'latitude' => -6.948412,
                'longitude' => 107.592412,
            ],
            [
                'kode_titik' => 'BM 147 (A)',
                'lokasi' => 'Jl. SIliwangi (area PGC)- CIrebon ',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Cirebon',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.714812,
                'longitude' => 108.558412,
            ],
            [
                'kode_titik' => 'BM 147 (B)',
                'lokasi' => 'Jl. SIliwangi (area PGC)- CIrebon ',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Cirebon',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.714901,
                'longitude' => 108.558502,
            ],
            [
                'kode_titik' => 'BM 148',
                'lokasi' => 'Jl. Terusan Prof Dr Sutami',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.884112,
                'longitude' => 107.584112,
            ],
            [
                'kode_titik' => 'BM 149',
                'lokasi' => 'Jl. Tanjung Pura, Karawang',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Karawang',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.304812,
                'longitude' => 107.304812,
            ],
            [
                'kode_titik' => 'BM 150',
                'lokasi' => 'Exit Tol Pasteur KM 00+600',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.890328446283732,
                'longitude' => 107.57470214262521,
            ],
            [
                'kode_titik' => 'BM 151 (A)',
                'lokasi' => 'Jl. KH Abdul Halim RT 002 RW 11, Majalengka Kulon, Majalengka (view menuju Majalengka)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Majalengka',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.834112,
                'longitude' => 108.221412,
            ],
            [
                'kode_titik' => 'BM 151 (B)',
                'lokasi' => 'Jl. KH Abdul Halim RT 002 RW 11, Majalengka Kulon, Majalengka (view menuju Bandung)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Majalengka',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.834201,
                'longitude' => 108.221502,
            ],
            [
                'kode_titik' => 'BM 152',
                'lokasi' => 'Exit Tol Soreang ( RM Dadakan Sunda )',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -7.021412,
                'longitude' => 107.528412,
            ],
            [
                'kode_titik' => 'BM 153',
                'lokasi' => 'Jl. Pasirkaliki No. 73 (depan RM Sederhana)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.908412,
                'longitude' => 107.598412,
            ],
            [
                'kode_titik' => 'BM 154',
                'lokasi' => 'Jl. Raya Cirebon - Bandung (Sumberjaya)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Majalengka',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.718412,
                'longitude' => 108.442412,
            ],
            [
                'kode_titik' => 'BM 155',
                'lokasi' => 'Jl. Raya Kuningan Cirebon (dekat Polsek Cilimus)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Kuningan',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.858412,
                'longitude' => 108.504812,
            ],
            [
                'kode_titik' => 'BM 156',
                'lokasi' => 'Neonbox CIlimus',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Neonbox',
                'kab_kota' => 'Kab. Kuningan',
                'harga_per_bulan' => 35000000,
                'status' => 'Tersedia',
                'latitude' => -6.859412,
                'longitude' => 108.505412,
            ],
            [
                'kode_titik' => 'BM 157',
                'lokasi' => 'Jl. Dewi Sartika, Tumudal, Sumberjaya, Cirebon',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Cirebon',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.721412,
                'longitude' => 108.448412,
            ],
            [
                'kode_titik' => 'BM 158',
                'lokasi' => 'Jl. Jakarta ( Kiara Artha )',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.914841,
                'longitude' => 107.641214,
            ],
            [
                'kode_titik' => 'BM 159',
                'lokasi' => 'Jl. Raya Soreang No.107,Soreang (depan Juara Sport)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -7.024812,
                'longitude' => 107.521412,
            ],
            [
                'kode_titik' => 'BM 160',
                'lokasi' => 'Jl. Ibrahim Adjie, Kiaracondong (sebelum BTM)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.942941,
                'longitude' => 107.636841,
            ],
            [
                'kode_titik' => 'BM 161',
                'lokasi' => 'Jl. LL RE Martadinata No. 61 ( 3 Second )',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.904812,
                'longitude' => 107.612412,
            ],
            [
                'kode_titik' => 'BM 162',
                'lokasi' => 'Jl. Pasirkaliki No. 45 Bandung',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.912412,
                'longitude' => 107.601421,
            ],
            [
                'kode_titik' => 'BM 163',
                'lokasi' => 'Jl. Ahmad Yani, Kiaracondong (Kaca Mobil)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.918412,
                'longitude' => 107.636841,
            ],
            [
                'kode_titik' => 'BM 164',
                'lokasi' => 'Jl. Raya, Salamnunggal, Leles (dekat Mesjid Agung Leles)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Garut',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -7.148412,
                'longitude' => 107.892412,
            ],
            [
                'kode_titik' => 'BM 165',
                'lokasi' => 'Jl. Raya Kadungora, Karangmulya, Kadungora',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Garut',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -7.118412,
                'longitude' => 107.884112,
            ],
            [
                'kode_titik' => 'BM 166',
                'lokasi' => 'Jl. Ahmad Yani, Garut',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Garut',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -7.214112,
                'longitude' => 107.904812,
            ],
            [
                'kode_titik' => 'BM 167',
                'lokasi' => 'Jl. Otista, Garut',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Garut',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -7.218412,
                'longitude' => 107.898412,
            ],
            [
                'kode_titik' => 'BM 168',
                'lokasi' => 'Jl. Raya Pacet, Cipendawa, Cianjur (Cipanas)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Cianjur',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.792412,
                'longitude' => 107.048412,
            ],
            [
                'kode_titik' => 'BM 169',
                'lokasi' => 'Jl. Raya Cibeber, Cihaur, CIbeber, Cianjur',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Cianjur',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.914812,
                'longitude' => 107.128412,
            ],
            [
                'kode_titik' => 'BM 170',
                'lokasi' => 'Jl. Raya Sukabumi (Warung Kondang), Cianjur',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Cianjur',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.858412,
                'longitude' => 107.104812,
            ],
            [
                'kode_titik' => 'BM 171',
                'lokasi' => 'Jl. Raya CIbeber, Sirnagalih, Cilaku, Cianjur (Pasir Hayam)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Cianjur',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.842412,
                'longitude' => 107.118412,
            ],
            [
                'kode_titik' => 'BM 172',
                'lokasi' => 'Jl. Raya Bandung RT 004 RW 05, Ciranjang, Ciranjang, Cianjur',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Cianjur',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.818412,
                'longitude' => 107.262412,
            ],
            [
                'kode_titik' => 'BM 173',
                'lokasi' => 'Jl. Raya Cipeuyeum, Kertasari, Haurwangi, Cianjur',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Cianjur',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.824112,
                'longitude' => 107.292412,
            ],
            [
                'kode_titik' => 'BM 175',
                'lokasi' => 'Jl. Sukajadi No. 80 (Vender Club)',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.884112,
                'longitude' => 107.594812,
            ],
            [
                'kode_titik' => 'BM 176 (A)',
                'lokasi' => 'Jl. Merdeka No. 56 Bandung',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.908412,
                'longitude' => 107.611412,
            ],
            [
                'kode_titik' => 'BMST 98',
                'lokasi' => 'JL. Siliwangi No. 154 rt.01 rw.17 kel.cibadak kec. Cibadak - Sukabumi ',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Sukabumi',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.924112,
                'longitude' => 106.792412,
            ],
            [
                'kode_titik' => 'BMST 100',
                'lokasi' => 'Jl. Raya Rancaekek Buah Dua -Kab. Bandung ',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kab. Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.948412,
                'longitude' => 107.768412,
            ],
            [
                'kode_titik' => 'BMST 103',
                'lokasi' => 'Jl. Ahmad Yani No. 909 - Cicaheum Bandung',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.899824,
                'longitude' => 107.641214,
            ],
            [
                'kode_titik' => 'BMST 133 (A)',
                'lokasi' => 'Jl. Tamansari No. 66 (Flyover Pasopati) -  Arah Pasteur - Gasibu ',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.898412,
                'longitude' => 107.611412,
            ],
            [
                'kode_titik' => 'BMST 133 (B)',
                'lokasi' => 'Jl. Tamansari No. 66 (Flyover Pasopati) -  Arah Gasibu - Pasteur',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.898501,
                'longitude' => 107.611502,
            ],
            [
                'kode_titik' => 'BST 85',
                'lokasi' => 'Jl. Pasir Kaliki No. 199 - Bandung (ST INTEN) ',
                'ukuran' => '4m x 8m (V)',
                'jenis_ooh' => 'Frontlite',
                'kab_kota' => 'Kota Bandung',
                'harga_per_bulan' => 30000000,
                'status' => 'Tersedia',
                'latitude' => -6.894214,
                'longitude' => 107.599812,
            ],
        ];

        // Membagi array menjadi chunk kecil berisi 20 data 
        // agar tidak terkena limitasi stack memory SQL pada saat insert massal
        foreach (array_chunk($billboards, 20) as $chunk) {
            DB::table('billboards')->upsert(
                $chunk, 
                ['kode_titik'], // Kolom unik yang menjadi acuan pengecekan
                ['lokasi', 'ukuran', 'jenis_ooh', 'kab_kota', 'harga_per_bulan', 'status', 'latitude', 'longitude'] // Kolom yang di-update jika duplikat
            );
        }
    }
}